input = "BxBCDCCCCCxxBDCDDDxAACBADBAxCxCABCBxBADBCBCBDBAAABADDCBCABxAACDBDDACCBBADCCAxBACBBBBxCABDAABBADxBBDBDCDADACCBCBxDCDADxCABxCDBCBCBxDACDxDCDBDCDBCxACACABDxxCCCxCxCAxBAADABACBBAADxDxCAxxCBBBBAABACADDACDAABAACCCDBxDCxACAxCACABCBBCADxAABxCDBCCBxDxDACDxBABBDCAABDBDxCBxCCxDDDACBxAAxDxBDACABCADDABxBBAACBADABCCDBDACAABxDCBABAACCADCADDDADCCBBADCCBACDxDDDCDAxCAABAxxBABDBBDxADBCADAADADDDDCDDAAABBCBDDACCACxxDCACCAADABBDBBCDCCAABBABBCBDDADDCABxADBDAACBCAACBDDDDABBABCBBACCACCBxDACBBADxxxAxCBBABBDCxACCDACCAAAxDAACBDAAAAxBCBDCDBBBCCBAxCCCDBCBADDDDBCCACCAABBDDDDCABAxABADADBABCAxADDCCDBDCDCADADDDCAxCCBxAAAACCDAxCAACxCxCxCDADAxBxDxDDABADACBDxBBABACxDDDCxxxABCCxABxCBDBDxABCAxCCCBxDxABBBDCCAAxBCBADABDDBDCxBDDADDCBxABDDCBBBDxADCDBDxBADBCxCBBBACxCBADDACAAAABBCAACCCAABCADBBBCxAADDCACBAABxCBCxBBABBABBDBDBACABBCxBABCDADDAACAACBCCAACDBAABACADAACABDCACDxBADACCDxDADCxDDCCDCxDxDCCCABABAACDCCCxBBxBDxABBADABBAxCBxCDxCDxCDxADDCBCDBDCBDBCCCCBBCDDCCADCABDACDCBBAxDxCDDCBDACDBxxDDABCDACACDxACBDxxDBxDBDADBADCDDCCAxAxBAACDDBDACABBCBAAABAACDBDACADCDADDBDxCCAABBADABCxDxADADCDAxCDCCCBxCDAADCDCCDBDABCBDCDDxCCDBxCxABDDBDDDDAxBADCBCBBCACDCCDAxCBCABBADBDADxADDCxDDBBDBxBAACBAAAABxCCxCCDACDCCCBCCBDBACxDADBDxDABCCDCCCBDCCACDAACAAABABACDADBCxxCBDBCADxBADCCADxABDBADAAxDBCBADBABCBBDDADABAxBBDBCAxDBBCAAAxCDBCCCBBDBDCxDBAxxBDDDADCCDCAADDBxABBBDACCCACBCAxCxADACBDBBDBBADxCCDBBABDCxxxDACCDDBAACDBBACDDxBxADCDBCxBAACAAADCBCDCAAAxxCCCBBBBCABDDBBBBCDCDADCBADCAxDBxBDDxBADBCxADCCACADADACCCBBBDABADxACDDDADCCDBDDBCABCCAxCCDCBCDDxABDCxCxBCAADxCDBBADCDAAxABAACDxBBCAACDDBxCBBBDCCCDABCAxCAADCxCDCBDCDCCBADBDACAxCBDBAxxxBDABxBDDBCCAAxACADDBCABDDBAAxBBABCDCADADACCDACBxCxxABAAxDxBAxDABADDAABDBxCCAxCBDBBxxAABABDxCBAADAACDxDBDCADADACCABADDBCAxCxCCCBxDxDBxBCBBDCABCCDACADAAADxxDBBAADAxAABDDCCxDACDADxACADACDCBACDABBBBBCBAAABBCABCDCCBDCBAxDBABxBBABCBxxADABCCDBABCCCDxBDDBDDBBACxCCDCCDDDCCDDBAABxDxBCxBxACCDBCACBDDCxADACDAxADDBAACCAxDCABxCBABCAxDxDDCCCDBCxBxDABBACDDBDABDCDCBBBBCCDDxCDxACDBCCBBxAxCBDAxAAxDAxxAxBDABBBBCDABAADDDACDBAxBBCCACDxDBxDDxCC"
potions = {'A': 0, 'B': 1, 'C': 3, 'D': 5}
total_potions = 0


for i in range(0, len(input), 2):
    char1 = input[i]
    char2 = input[i + 1]
    if char1 != 'x' and char2 != 'x':
        pair_potions = potions[char1] + potions[char2] + 2
    else:
        if char1 == 'x':
            value1 =0
        else:
            value1 = potions[char1]
        if char2 == 'x':
            value2 =0
        else:
            value2 = potions[char2]
        pair_potions = value1 + value2    

    total_potions += pair_potions

    
print(total_potions)